/* tslint:disable */
/* eslint-disable */
/**
 * Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'

/**
 *
 * @export
 * @interface BlogPostDto
 */
export interface BlogPostDto {
  /**
   *
   * @type {number}
   * @memberof BlogPostDto
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof BlogPostDto
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof BlogPostDto
   */
  createdAt: string;
  /**
   *
   * @type {string}
   * @memberof BlogPostDto
   */
  updatedAt: string;
  /**
   *
   * @type {string}
   * @memberof BlogPostDto
   */
  content: string;
}

export function BlogPostDtoFromJSON(json: any): BlogPostDto {
  return BlogPostDtoFromJSONTyped(json, false)
}

export function BlogPostDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlogPostDto {
  if ((json === undefined) || (json === null)) {
    return json
  }
  return {

    'id': json['id'],
    'title': json['title'],
    'createdAt': json['createdAt'],
    'updatedAt': json['updatedAt'],
    'content': json['content'],
  }
}

export function BlogPostDtoToJSON(value?: BlogPostDto | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {

    'id': value.id,
    'title': value.title,
    'createdAt': value.createdAt,
    'updatedAt': value.updatedAt,
    'content': value.content,
  }
}

