/* tslint:disable */
/* eslint-disable */
/**
 * Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'

/**
 *
 * @export
 * @interface BlogPostPreviewDto
 */
export interface BlogPostPreviewDto {
  /**
   *
   * @type {number}
   * @memberof BlogPostPreviewDto
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof BlogPostPreviewDto
   */
  title: string;
}

export function BlogPostPreviewDtoFromJSON(json: any): BlogPostPreviewDto {
  return BlogPostPreviewDtoFromJSONTyped(json, false)
}

export function BlogPostPreviewDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlogPostPreviewDto {
  if ((json === undefined) || (json === null)) {
    return json
  }
  return {

    'id': json['id'],
    'title': json['title'],
  }
}

export function BlogPostPreviewDtoToJSON(value?: BlogPostPreviewDto | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {

    'id': value.id,
    'title': value.title,
  }
}

