/* tslint:disable */
/* eslint-disable */
/**
 * Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */
export enum EvolveCharacter {
  Abe = 'ABE',
  Bucket = 'BUCKET',
  Cabot = 'CABOT',
  Caira = 'CAIRA',
  Crow = 'CROW',
  Emet = 'EMET',
  Griffin = 'GRIFFIN',
  Hank = 'HANK',
  Hyde = 'HYDE',
  Lazarus = 'LAZARUS',
  Lennox = 'LENNOX',
  Maggie = 'MAGGIE',
  Markov = 'MARKOV',
  Parnell = 'PARNELL',
  Scrap = 'SCRAP',
  Slim = 'SLIM',
  Sunny = 'SUNNY',
  Tech = 'TECH',
  Torvald = 'TORVALD',
  Val = 'VAL'
}

export function EvolveCharacterFromJSON(json: any): EvolveCharacter {
  return EvolveCharacterFromJSONTyped(json, false)
}

export function EvolveCharacterFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvolveCharacter {
  return json as EvolveCharacter
}

export function EvolveCharacterToJSON(value?: EvolveCharacter | null): any {
  return value as any
}

