/* tslint:disable */
/* eslint-disable */
/**
 * Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from '../runtime'

/**
 *
 * @export
 * @interface EvolveDialogueDto
 */
export interface EvolveDialogueDto {
  /**
   *
   * @type {string}
   * @memberof EvolveDialogueDto
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof EvolveDialogueDto
   */
  text: string;
  /**
   *
   * @type {Array<string>}
   * @memberof EvolveDialogueDto
   */
  audio?: Array<string> | null;
}

export function EvolveDialogueDtoFromJSON(json: any): EvolveDialogueDto {
  return EvolveDialogueDtoFromJSONTyped(json, false)
}

export function EvolveDialogueDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvolveDialogueDto {
  if ((json === undefined) || (json === null)) {
    return json
  }
  return {

    'name': json['name'],
    'text': json['text'],
    'audio': !exists(json, 'audio') ? undefined : json['audio'],
  }
}

export function EvolveDialogueDtoToJSON(value?: EvolveDialogueDto | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {

    'name': value.name,
    'text': value.text,
    'audio': value.audio,
  }
}


