version: "3.7"
services:

  db:
    image: postgres:11.7
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=dev
    networks:
      - backend

  nginx:
    image: nginx:1.17.9
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./../../dist:/var/www/static
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=q6kfjhnpdimvjhkrk2fm.senpai.online
      - NGINX_PORT=80
    command: ["nginx", "-g", "daemon off;"]
    networks:
      backend: {}

networks:
  backend:

volumes:
  db-data:
